### ISSUE TITLE
[BUG] UnsupportedEncodingException arises based on input size in contentToValidate

### ISSUE THREAD

**Issue by adrian-haenni** [ISAITB/csv-validator#1]
The used Tika charset detection is unreliable. I made some domain definition and used the API to validate some CSVs with `embeddingMethod: "STRING"`.  Depending on the size of the input an UnsupportedEncodingException is thrown as it detects `IBM420_ltr` as charset which is wrong . I used the same data and uploaded different chunks. If I validate only few lines of the same data in chucks the validation is successful, however uploading the whole content results in an exception.

The cause of the issue is in class `eu.europa.ec.itb.csv.validation.CSVValidator` at line 418, respectively in the method `getCharsetToUse()`.

Please either add an option to manually define the charset as input parameter to the API or in the schema json definition or implement a bugfix.

### Error
```shell
csv-1  | 10/10/2024 08:03:30 ERROR [test] o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/csv] threw exception [Request processing failed: eu.europa.ec.itb.validation.commons.error.ValidatorException: Unable to read the provided input file] with root cause
csv-1  | java.io.UnsupportedEncodingException: IBM420_ltr
csv-1  |        at java.base/sun.nio.cs.StreamDecoder.forInputStreamReader(Unknown Source)
csv-1  |        at java.base/java.io.InputStreamReader.<init>(Unknown Source)
csv-1  |        at eu.europa.ec.itb.csv.validation.CSVValidator.prepareInputFile(CSVValidator.java:423)
csv-1  |        at eu.europa.ec.itb.csv.validation.CSVValidator.validateInternal(CSVValidator.java:173)
csv-1  |        at eu.europa.ec.itb.csv.validation.CSVValidator.validate(CSVValidator.java:99)
csv-1  |        at eu.europa.ec.itb.csv.rest.RestValidationController.executeValidationProcess(RestValidationController.java:185)
csv-1  |        at eu.europa.ec.itb.csv.rest.RestValidationController.validate(RestValidationController.java:126)
csv-1  |        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
csv-1  |        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
csv-1  |        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
csv-1  |        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
csv-1  |        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
csv-1  |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
csv-1  |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
csv-1  |        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
csv-1  |        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
csv-1  |        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
csv-1  |        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
csv-1  |        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
csv-1  |        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
csv-1  |        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
csv-1  |        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at eu.europa.ec.itb.validation.commons.war.filters.LoggingFilter.doFilter(LoggingFilter.java:22)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:66)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at eu.europa.ec.itb.validation.commons.web.filters.HeaderFilter.doFilterInternal(HeaderFilter.java:52)
csv-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at eu.europa.ec.itb.validation.commons.web.filters.DomainCheckFilter.doFilterInternal(DomainCheckFilter.java:67)
csv-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
csv-1  |        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
csv-1  |        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
csv-1  |        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
csv-1  |        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
csv-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
csv-1  |        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
csv-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at eu.europa.ec.itb.validation.commons.web.CSPNonceFilter.doFilter(CSPNonceFilter.java:37)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
csv-1  |        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
csv-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
csv-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
csv-1  |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
csv-1  |        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
csv-1  |        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
csv-1  |        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
csv-1  |        at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
csv-1  |        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
csv-1  |        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
csv-1  |        at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230)
csv-1  |        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
csv-1  |        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
csv-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
csv-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
csv-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
csv-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
csv-1  |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
csv-1  |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
csv-1  |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
csv-1  |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
csv-1  |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
csv-1  |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
csv-1  |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
csv-1  |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384)
csv-1  |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
csv-1  |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
csv-1  |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
csv-1  |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
csv-1  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
csv-1  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
csv-1  |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
csv-1  |        at java.base/java.lang.Thread.run(Unknown Source)
csv-1  | 10/10/2024 08:04:30 INFO  [test] e.e.e.i.csv.validation.CSVValidator - Converted input file from [ISO-8859-2] to [UTF-8].
 
```
### Content & configuration

For the domain `test`:

test/schemas/v1.0.0/test.schema.json

```json
{
  "fields": [
    {
      "name": "Date",
      "type": "date",
      "description": "Date in DD.MM.YYYY format",
      "format": "%d.%m.%Y",
      "constraints": {
        "required": true
      }
    },
    {
      "name": "Time",
      "type": "time",
      "description": "Time in HH:MM format",
      "format": "%H:%M",
      "constraints": {
        "required": true
      }
    },
    {
      "name": "Value",
      "type": "float",
      "description": "The value",
      "constraints": {
        "required": true,
        "pattern": "^\\d+\\.\\d+$"
      }
    },
    {
      "name": "Status",
      "type": "string",
      "description": "The status",
      "constraints": {
        "required": true,
        "pattern": "^[a-zA-Z]$"
      }
    }
  ]
}

```

test/config.properties

```
validator.type = basic
validator.typeLabel.basic = Basic monthly
validator.typeOptions.basic = v1.0.0
validator.schemaFile.basic.v1.0.0 = schemas/v1.0.0/test.schema.json
validator.uploadTitle = Test
validator.delimiter.basic.v1.0.0 = ;
validator.hasHeaders.basic.v1.0.0 = false
```

### To reproduce

API Request which does not work:

````shell
curl -X 'POST' \
  'http://localhost:8080/csv/test/api/validate' \
  -H 'accept: application/xml' \
  -H 'Content-Type: application/json' \
  -d '{
  "contentToValidate": "08.10.2024;05:00;0.000000;W\r\n08.10.2024;06:00;0.000000;W\r\n08.10.2024;07:00;4.670000;W\r\n08.10.2024;08:00;3.560000;W\r\n08.10.2024;09:00;3.990000;W\r\n08.10.2024;10:00;2.410000;W\r\n08.10.2024;11:00;3.850000;W\r\n08.10.2024;12:00;0.920000;W\r\n08.10.2024;13:00;3.290000;W\r\n08.10.2024;14:00;2.370000;W\r\n08.10.2024;15:00;3.440000;W\r\n08.10.2024;16:00;1.640000;W\r\n08.10.2024;17:00;1.370000;W\r\n08.10.2024;18:00;4.920000;W\r\n08.10.2024;19:00;2.810000;W\r\n08.10.2024;20:00;2.620000;W\r\n08.10.2024;21:00;2.070000;W\r\n08.10.2024;22:00;4.910000;W\r\n08.10.2024;23:00;0.530000;W\r\n09.10.2024;00:00;0.000000;W\r\n09.10.2024;01:00;0.000000;W\r\n09.10.2024;02:00;0.000000;W\r\n09.10.2024;03:00;0.000000;W\r\n09.10.2024;04:00;0.000000;W",
  "validationType": "basic.v1.0.0"
}'
````

API Request which does work:

````shell
curl -X 'POST' \
  'http://localhost:8080/csv/test/api/validate' \
  -H 'accept: application/xml' \
  -H 'Content-Type: application/json' \
  -d '{
  "contentToValidate": "09.10.2024;02:00;0.000000;W\r\n09.10.2024;03:00;0.000000;W\r\n09.10.2024;04:00;0.000000;W",
  "validationType": "basic.v1.0.0"
}'
````

**Comment by adrian-haenni** [comment]
Thank you, @costas80, for the prompt response and bug fix. I can confirm that my example is now working. You can mark the issue as resolved.
